In [105]:
import numpy as np
import pandas as pd 
from sklearn.impute import SimpleImputer

In [106]:
df = pd.read_csv("E:\ML GFG\Data Analysis\googleplaystore.csv")

In [107]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [108]:
impute = SimpleImputer(missing_values = np.nan, strategy = 'mean')
impute.fit(df.iloc[:, 2:3].values)
df.iloc[:, 2:3] = impute.transform(df.iloc[:, 2:3].values)

df = df.dropna()

In [109]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [110]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,4.193338,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

# Q1. How many free apps are there in ART_AND_DESIGN

In [111]:
df = df.values

In [112]:
df[1]

array(['Coloring book moana', 'ART_AND_DESIGN', 3.9, '967', '14M',
       '500,000+', 'Free', '0', 'Everyone', 'Art & Design;Pretend Play',
       'January 15, 2018', '2.0.0', '4.0.3 and up'], dtype=object)

In [113]:
c = 0
for i in df:
    if i[1] == 'ART_AND_DESIGN' and i[6] == 'Free':
        c += 1

print("There are", c, "Free apps from ART_AND_DESIGN")

There are 61 Free apps from ART_AND_DESIGN

In [114]:
c = 0
for i in df:
    if i[1] == 'ART_AND_DESIGN' and i[6] == 'Paid':
        c += 1

print("There are", c, "Paid apps from ART_AND_DESIGN")

There are 3 Paid apps from ART_AND_DESIGN

# Q2. How Many Apps are there ART_AND_DESIGN with rating more than 4.5

In [115]:
c = 0
for i in df:
    if i[1] == 'ART_AND_DESIGN' and i[2] > 4.5:
        c += 1

print("There are", c, "Rating is greater than 4.5 apps from ART_AND_DESIGN")

There are 22 Rating is greater than 4.5 apps from ART_AND_DESIGN

# Q3. How many apps are there in FAMILY with rating more than 4.5 and Free?

In [116]:
c = 0
for i in df:
    if (i[1] == 'ART_AND_DESIGN' and i[2] > 4.5 and i[6]=='Free'):
        c += 1

print("There are", c, "Rating is greater than 4.5 apps from ART_AND_DESIGN")

There are 19 Rating is greater than 4.5 apps from ART_AND_DESIGN

# Q4. List all the free apps where rating more than 4.5 and category is FAMILY?

In [117]:
print('*'*30)
print("These are the apps where category is FAMILY with rating more than 4.5")
print('*'*30)
for i in df:
    if (i[1] == 'ART_AND_DESIGN' and i[2] > 4.5 and i[6]=='Free'):
        print(i[0])
print('*'*30)

******************************
These are the apps where category is FAMILY with rating more than 4.5
******************************
U Launcher Lite – FREE Live Cool Themes, Hide Apps
Kids Paint Free - Drawing Fun
Mandala Coloring Book
Photo Designer - Write your name with shapes
ibis Paint X
Superheroes Wallpapers | 4K Backgrounds
HD Mickey Minnie Wallpapers
Harley Quinn wallpapers HD
Colorfit - Drawing & Coloring
I Creative Idea
UNICORN - Color By Number & Pixel Art Coloring
PIP Camera - PIP Collage Maker
Canva: Poster, banner, card maker & graphic design
Install images with music to make video without Net - 2018
Cardi B Wallpaper
X Launcher: With OS11 Style Theme & Control Center
AJ Styles HD Wallpapers
Fantasy theme dark bw black building
Spring flowers theme couleurs d t space
******************************

# Q1. How many free apps are there in ART_AND_DESIGN Using Pandas

In [120]:
import pandas as pd

In [121]:
df = pd.read_csv("E:\ML GFG\Data Analysis\googleplaystore.csv")

In [122]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [125]:
df[df['Category'] == 'BOOKS_AND_REFERENCE']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
139,Wattpad 📖 Free Books,BOOKS_AND_REFERENCE,4.6,2914724,Varies with device,"100,000,000+",Free,0,Teen,Books & Reference,"August 1, 2018",Varies with device,Varies with device
140,E-Book Read - Read Book for free,BOOKS_AND_REFERENCE,4.5,1857,4.9M,"50,000+",Free,0,Everyone,Books & Reference,"August 3, 2018",1.3.2,4.4 and up
141,Download free book with green book,BOOKS_AND_REFERENCE,4.6,4478,9.5M,"100,000+",Free,0,Everyone 10+,Books & Reference,"July 31, 2017",1.1,4.0 and up
142,Wikipedia,BOOKS_AND_REFERENCE,4.4,577550,Varies with device,"10,000,000+",Free,0,Everyone,Books & Reference,"August 2, 2018",Varies with device,Varies with device
143,Amazon Kindle,BOOKS_AND_REFERENCE,4.2,814080,Varies with device,"100,000,000+",Free,0,Teen,Books & Reference,"July 27, 2018",Varies with device,Varies with device
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10815,Golden Dictionary (FR-AR),BOOKS_AND_REFERENCE,4.2,5775,4.9M,"500,000+",Free,0,Everyone,Books & Reference,"July 19, 2018",7.0.4.6,4.2 and up
10819,Fanfic-FR,BOOKS_AND_REFERENCE,3.3,52,3.6M,"5,000+",Free,0,Teen,Books & Reference,"August 5, 2017",0.3.4,4.1 and up
10829,Bulgarian French Dictionary Fr,BOOKS_AND_REFERENCE,4.6,603,7.4M,"10,000+",Free,0,Everyone,Books & Reference,"June 19, 2016",2.96,4.1 and up
10833,Chemin (fr),BOOKS_AND_REFERENCE,4.8,44,619k,"1,000+",Free,0,Everyone,Books & Reference,"March 23, 2014",0.8,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device

In [126]:
df[df['Category'] == 'ART_AND_DESIGN']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7174,Easy DIY CD Craft Ideas,ART_AND_DESIGN,NaN,7,5.6M,"5,000+",Free,0,Everyone,Art & Design,"May 30, 2018",1.0,2.3 and up
8679,Dp for girls,ART_AND_DESIGN,4.2,175,8.2M,"50,000+",Free,0,Everyone,Art & Design,"May 26, 2017",1.2,4.0.3 and up
8712,Name Art DP - Focus n Filter Text 2018,ART_AND_DESIGN,4.3,132,7.7M,"10,000+",Free,0,Everyone,Art & Design,"January 4, 2018",1,4.1 and up
8871,Test Application DT 02,ART_AND_DESIGN,NaN,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

# Q2. How Many Apps are there ART_AND_DESIGN with rating more than 4.5 using Pandas

In [128]:
df[df['Category'] == 'ART_AND_DESIGN']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7174,Easy DIY CD Craft Ideas,ART_AND_DESIGN,NaN,7,5.6M,"5,000+",Free,0,Everyone,Art & Design,"May 30, 2018",1.0,2.3 and up
8679,Dp for girls,ART_AND_DESIGN,4.2,175,8.2M,"50,000+",Free,0,Everyone,Art & Design,"May 26, 2017",1.2,4.0.3 and up
8712,Name Art DP - Focus n Filter Text 2018,ART_AND_DESIGN,4.3,132,7.7M,"10,000+",Free,0,Everyone,Art & Design,"January 4, 2018",1,4.1 and up
8871,Test Application DT 02,ART_AND_DESIGN,NaN,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

In [130]:
df_pr = df[df['Category'] == 'ART_AND_DESIGN']

In [131]:
df_pr[df_pr['Type']=='Free']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7174,Easy DIY CD Craft Ideas,ART_AND_DESIGN,NaN,7,5.6M,"5,000+",Free,0,Everyone,Art & Design,"May 30, 2018",1.0,2.3 and up
8679,Dp for girls,ART_AND_DESIGN,4.2,175,8.2M,"50,000+",Free,0,Everyone,Art & Design,"May 26, 2017",1.2,4.0.3 and up
8712,Name Art DP - Focus n Filter Text 2018,ART_AND_DESIGN,4.3,132,7.7M,"10,000+",Free,0,Everyone,Art & Design,"January 4, 2018",1,4.1 and up
8871,Test Application DT 02,ART_AND_DESIGN,NaN,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

In [132]:
print(len(df_pr))

65

In [133]:
df_rat = df_pr[df_pr['Rating']> 4.5]

In [134]:
len(df_rat)

22

# Q3. How many apps are there in FAMILY with rating more than 4.5 and Free? Using Pandas

In [144]:
df_pr = df[df['Category'] == 'FAMILY']
df_pr = df_pr[df_pr['Rating']> 4.5]
df_pr = df[df['Type'] == 'Free']

In [145]:
len(df_rat)

364

# Q4. List all the free apps where rating more than 4.5 and category is FAMILY?

In [150]:
df_pr = df[df['Category'] == 'FAMILY']
df_pr = df_pr[df_pr['Rating']> 4.5]
df_pr[df_pr['Type'] == 'Free']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2020,Super ABC! Learning games for kids! Preschool ...,FAMILY,4.6,20267,46M,"1,000,000+",Free,0,Everyone,Educational;Education,"July 16, 2018",1.1.6.7,4.1 and up
2023,Candy Pop Story,FAMILY,4.7,12948,23M,"1,000,000+",Free,0,Everyone,Casual;Brain Games,"May 24, 2018",2.0.3165,2.3 and up
2029,Dog Run - Pet Dog Simulator,FAMILY,4.7,48615,24M,"10,000,000+",Free,0,Everyone,Simulation;Action & Adventure,"May 22, 2018",1.4.12,4.1 and up
2032,Puzzle Kids - Animals Shapes and Jigsaw Puzzles,FAMILY,4.6,1109,52M,"1,000,000+",Free,0,Everyone,Educational;Brain Games,"July 18, 2018",1.0.6,4.1 and up
2040,"No. Color - Color by Number, Number Coloring",FAMILY,4.8,269194,6.9M,"10,000,000+",Free,0,Everyone,Entertainment;Brain Games,"August 3, 2018",Varies with device,Varies with device
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10691,Pin-fo,FAMILY,4.6,19,1.6M,500+,Free,0,Everyone,Entertainment,"August 15, 2016",3rd Release Aug 2016,2.2 and up
10801,Fr Ignacio Outreach,FAMILY,4.9,52,19M,"1,000+",Free,0,Everyone,Education,"January 19, 2018",1.0,4.4 and up
10809,Castle Clash: RPG War and Strategy FR,FAMILY,4.7,376223,24M,"1,000,000+",Free,0,Everyone,Strategy,"July 18, 2018",1.4.2,4.1 and up
10820,Fr. Daoud Lamei,FAMILY,5.0,22,8.6M,"1,000+",Free,0,Teen,Education,"June 27, 2018",3.8.0,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up