In [1]:
import numpy as np
import pandas as pd 
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv("E:\ML GFG\Data Analysis\googleplaystore.csv")

In [3]:
impute = SimpleImputer(missing_values = np.nan, strategy = 'mean')
impute.fit(df.iloc[:, 2:3].values)
df.iloc[:, 2:3] = impute.transform(df.iloc[:, 2:3].values)

df = df.dropna()

In [4]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [5]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

# Q1. Name the apps that are in ART_AND_DESIGN with rating more than 4.5 in ascending order WRT Ratings ?

In [7]:
df_pr = df[df['Category']=='ART_AND_DESIGN']
df_pr = df_pr[df_pr['Rating']>4.5]

In [8]:
df_pr

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
16,Photo Designer - Write your name with shapes,ART_AND_DESIGN,4.7,3632,5.5M,"500,000+",Free,0,Everyone,Art & Design,"July 31, 2018",3.1,4.1 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up
22,Superheroes Wallpapers | 4K Backgrounds,ART_AND_DESIGN,4.7,7699,4.2M,"500,000+",Free,0,Everyone 10+,Art & Design,"July 12, 2018",2.2.6.2,4.0.3 and up
24,HD Mickey Minnie Wallpapers,ART_AND_DESIGN,4.7,118,23M,"50,000+",Free,0,Everyone,Art & Design,"July 7, 2018",1.1.3,4.1 and up
25,Harley Quinn wallpapers HD,ART_AND_DESIGN,4.8,192,6.0M,"10,000+",Free,0,Everyone,Art & Design,"April 25, 2018",1.5,3.0 and up
26,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260,25M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"October 11, 2017",1.0.8,4.0.3 and up
34,I Creative Idea,ART_AND_DESIGN,4.7,353,4.2M,"10,000+",Free,0,Teen,Art & Design,"April 27, 2018",1.6,4.1 and up
36,UNICORN - Color By Number & Pixel Art Coloring,ART_AND_DESIGN,4.7,8145,24M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"August 2, 2018",1.0.9,4.4 and up
38,PIP Camera - PIP Collage Maker,ART_AND_DESIGN,4.7,158,11M,"10,000+",Free,0,Everyone,Art & Design,"November 29, 2017",1.3,4.0.3 and up
45,"Canva: Poster, banner, card maker & graphic de...",ART_AND_DESIGN,4.7,174531,24M,"10,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.6.1,4.1 and up
46,Install images with music to make video withou...,ART_AND_DESIGN,4.6,1070,26M,"100,000+",Free,0,Everyone,Art & Design,"November 14, 2017",1.6,4.1 and up
3982,Cardi B Wallpaper,ART_AND_DESIGN,4.8,253,3.7M,"50,000+",Free,0,Everyone,Art & Design,"November 1, 2017",1.0.0,4.0 and up
4749,X Launcher: With OS11 Style Theme & Control Ce...,ART_AND_DESIGN,4.7,5754,4.4M,"100,000+",Free,0,Everyone,Art & Design,"July 30, 2018",2.1.2,4.1 and up
4755,"X Launcher Pro: PhoneX Theme, OS11 Control Center",ART_AND_DESIGN,4.7,801,3.5M,"5,000+",Paid,$1.99,Everyone,Art & Design,"July 30, 2018",2.1.2,4.1 and up
4759,X Launcher Pro - IOS Style Theme & Control Center,ART_AND_DESIGN,4.8,1216,8.6M,"10,000+",Paid,$1.99,Everyone,Art & Design,"June 26, 2018",1.0.0,4.1 and up
4764,X Launcher Prime: With OS Style Theme & No Ads,ART_AND_DESIGN,4.7,149,3.5M,"1,000+",Paid,$1.99,Everyone,Art & Design,"July 30, 2018",1.2.2,4.1 and up
5254,AJ Styles HD Wallpapers,ART_AND_DESIGN,4.8,48,25M,"5,000+",Free,0,Everyone,Art & Design,"August 4, 2018",1.1.1,4.1 and up
6930,Fantasy theme dark bw black building,ART_AND_DESIGN,4.8,41,1.9M,"5,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.0.2,4.0 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

In [9]:
df_pr.sort_values(by ='Rating', ascending = True)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up
46,Install images with music to make video withou...,ART_AND_DESIGN,4.6,1070,26M,"100,000+",Free,0,Everyone,Art & Design,"November 14, 2017",1.6,4.1 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
16,Photo Designer - Write your name with shapes,ART_AND_DESIGN,4.7,3632,5.5M,"500,000+",Free,0,Everyone,Art & Design,"July 31, 2018",3.1,4.1 and up
22,Superheroes Wallpapers | 4K Backgrounds,ART_AND_DESIGN,4.7,7699,4.2M,"500,000+",Free,0,Everyone 10+,Art & Design,"July 12, 2018",2.2.6.2,4.0.3 and up
24,HD Mickey Minnie Wallpapers,ART_AND_DESIGN,4.7,118,23M,"50,000+",Free,0,Everyone,Art & Design,"July 7, 2018",1.1.3,4.1 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
38,PIP Camera - PIP Collage Maker,ART_AND_DESIGN,4.7,158,11M,"10,000+",Free,0,Everyone,Art & Design,"November 29, 2017",1.3,4.0.3 and up
26,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260,25M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"October 11, 2017",1.0.8,4.0.3 and up
36,UNICORN - Color By Number & Pixel Art Coloring,ART_AND_DESIGN,4.7,8145,24M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"August 2, 2018",1.0.9,4.4 and up
34,I Creative Idea,ART_AND_DESIGN,4.7,353,4.2M,"10,000+",Free,0,Teen,Art & Design,"April 27, 2018",1.6,4.1 and up
4749,X Launcher: With OS11 Style Theme & Control Ce...,ART_AND_DESIGN,4.7,5754,4.4M,"100,000+",Free,0,Everyone,Art & Design,"July 30, 2018",2.1.2,4.1 and up
45,"Canva: Poster, banner, card maker & graphic de...",ART_AND_DESIGN,4.7,174531,24M,"10,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.6.1,4.1 and up
4764,X Launcher Prime: With OS Style Theme & No Ads,ART_AND_DESIGN,4.7,149,3.5M,"1,000+",Paid,$1.99,Everyone,Art & Design,"July 30, 2018",1.2.2,4.1 and up
4755,"X Launcher Pro: PhoneX Theme, OS11 Control Center",ART_AND_DESIGN,4.7,801,3.5M,"5,000+",Paid,$1.99,Everyone,Art & Design,"July 30, 2018",2.1.2,4.1 and up
3982,Cardi B Wallpaper,ART_AND_DESIGN,4.8,253,3.7M,"50,000+",Free,0,Everyone,Art & Design,"November 1, 2017",1.0.0,4.0 and up
25,Harley Quinn wallpapers HD,ART_AND_DESIGN,4.8,192,6.0M,"10,000+",Free,0,Everyone,Art & Design,"April 25, 2018",1.5,3.0 and up
4759,X Launcher Pro - IOS Style Theme & Control Center,ART_AND_DESIGN,4.8,1216,8.6M,"10,000+",Paid,$1.99,Everyone,Art & Design,"June 26, 2018",1.0.0,4.1 and up
5254,AJ Styles HD Wallpapers,ART_AND_DESIGN,4.8,48,25M,"5,000+",Free,0,Everyone,Art & Design,"August 4, 2018",1.1.1,4.1 and up
6930,Fantasy theme dark bw black building,ART_AND_DESIGN,4.8,41,1.9M,"5,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.0.2,4.0 and up
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up

In [10]:
df_pr.sort_values(by ='Rating', ascending = False)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up
6930,Fantasy theme dark bw black building,ART_AND_DESIGN,4.8,41,1.9M,"5,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.0.2,4.0 and up
5254,AJ Styles HD Wallpapers,ART_AND_DESIGN,4.8,48,25M,"5,000+",Free,0,Everyone,Art & Design,"August 4, 2018",1.1.1,4.1 and up
3982,Cardi B Wallpaper,ART_AND_DESIGN,4.8,253,3.7M,"50,000+",Free,0,Everyone,Art & Design,"November 1, 2017",1.0.0,4.0 and up
25,Harley Quinn wallpapers HD,ART_AND_DESIGN,4.8,192,6.0M,"10,000+",Free,0,Everyone,Art & Design,"April 25, 2018",1.5,3.0 and up
4759,X Launcher Pro - IOS Style Theme & Control Center,ART_AND_DESIGN,4.8,1216,8.6M,"10,000+",Paid,$1.99,Everyone,Art & Design,"June 26, 2018",1.0.0,4.1 and up
34,I Creative Idea,ART_AND_DESIGN,4.7,353,4.2M,"10,000+",Free,0,Teen,Art & Design,"April 27, 2018",1.6,4.1 and up
45,"Canva: Poster, banner, card maker & graphic de...",ART_AND_DESIGN,4.7,174531,24M,"10,000,000+",Free,0,Everyone,Art & Design,"July 31, 2018",1.6.1,4.1 and up
22,Superheroes Wallpapers | 4K Backgrounds,ART_AND_DESIGN,4.7,7699,4.2M,"500,000+",Free,0,Everyone 10+,Art & Design,"July 12, 2018",2.2.6.2,4.0.3 and up
16,Photo Designer - Write your name with shapes,ART_AND_DESIGN,4.7,3632,5.5M,"500,000+",Free,0,Everyone,Art & Design,"July 31, 2018",3.1,4.1 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
26,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260,25M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"October 11, 2017",1.0.8,4.0.3 and up
24,HD Mickey Minnie Wallpapers,ART_AND_DESIGN,4.7,118,23M,"50,000+",Free,0,Everyone,Art & Design,"July 7, 2018",1.1.3,4.1 and up
4755,"X Launcher Pro: PhoneX Theme, OS11 Control Center",ART_AND_DESIGN,4.7,801,3.5M,"5,000+",Paid,$1.99,Everyone,Art & Design,"July 30, 2018",2.1.2,4.1 and up
4749,X Launcher: With OS11 Style Theme & Control Ce...,ART_AND_DESIGN,4.7,5754,4.4M,"100,000+",Free,0,Everyone,Art & Design,"July 30, 2018",2.1.2,4.1 and up
38,PIP Camera - PIP Collage Maker,ART_AND_DESIGN,4.7,158,11M,"10,000+",Free,0,Everyone,Art & Design,"November 29, 2017",1.3,4.0.3 and up
36,UNICORN - Color By Number & Pixel Art Coloring,ART_AND_DESIGN,4.7,8145,24M,"500,000+",Free,0,Everyone,Art & Design;Creativity,"August 2, 2018",1.0.9,4.4 and up
4764,X Launcher Prime: With OS Style Theme & No Ads,ART_AND_DESIGN,4.7,149,3.5M,"1,000+",Paid,$1.99,Everyone,Art & Design,"July 30, 2018",1.2.2,4.1 and up
13,Mandala Coloring Book,ART_AND_DESIGN,4.6,4326,21M,"100,000+",Free,0,Everyone,Art & Design,"June 26, 2018",1.0.4,4.4 and up
19,ibis Paint X,ART_AND_DESIGN,4.6,224399,31M,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",5.5.4,4.1 and up
46,Install images with music to make video withou...,ART_AND_DESIGN,4.6,1070,26M,"100,000+",Free,0,Everyone,Art & Design,"November 14, 2017",1.6,4.1 and up

In [11]:
df_pr = df[df['Category']=='ART_AND_DESIGN']
df_pr = df_pr[df_pr['Rating']>4.5]
df_pr.sort_values(by ='Rating', ascending = False).head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Free,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up
6930,Fantasy theme dark bw black building,ART_AND_DESIGN,4.8,41,1.9M,"5,000+",Free,0,Everyone,Art & Design,"March 20, 2018",1.0.2,4.0 and up
5254,AJ Styles HD Wallpapers,ART_AND_DESIGN,4.8,48,25M,"5,000+",Free,0,Everyone,Art & Design,"August 4, 2018",1.1.1,4.1 and up
3982,Cardi B Wallpaper,ART_AND_DESIGN,4.8,253,3.7M,"50,000+",Free,0,Everyone,Art & Design,"November 1, 2017",1.0.0,4.0 and up
25,Harley Quinn wallpapers HD,ART_AND_DESIGN,4.8,192,6.0M,"10,000+",Free,0,Everyone,Art & Design,"April 25, 2018",1.5,3.0 and up

# Q2. Which Category is having maximum average rating?

In [12]:
df['Category'].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION'],
      dtype=object)

In [16]:
df.groupby('Category')['Rating'].mean()

Category
ART_AND_DESIGN         4.368438
AUTO_AND_VEHICLES      4.190824
BEAUTY                 4.260882
BOOKS_AND_REFERENCE    4.311537
BUSINESS               4.145987
COMICS                 4.156445
COMMUNICATION          4.163842
DATING                 4.007864
EDUCATION              4.387778
ENTERTAINMENT          4.126174
EVENTS                 4.363647
FAMILY                 4.192490
FINANCE                4.139108
FOOD_AND_DRINK         4.170709
GAME                   4.282506
HEALTH_AND_FITNESS     4.266296
HOUSE_AND_HOME         4.196819
LIBRARIES_AND_DEMO     4.182938
LIFESTYLE              4.112427
MAPS_AND_NAVIGATION    4.065061
MEDICAL                4.190167
NEWS_AND_MAGAZINES     4.142993
PARENTING              4.282223
PERSONALIZATION        4.306873
PHOTOGRAPHY            4.192179
PRODUCTIVITY           4.208287
SHOPPING               4.254052
SOCIAL                 4.248001
SPORTS                 4.218404
TOOLS                  4.065970
TRAVEL_AND_LOCAL       4.119716
VIDEO_PLAYERS          4.074858
WEATHER                4.239675
Name: Rating, dtype: float64

# Q3. How many Free apps in there in each category

In [21]:
df.groupby('Category')['Type'].count().sort_values(ascending = False)

Category
FAMILY                 1968
GAME                   1144
TOOLS                   841
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         390
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     230
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       84
WEATHER                  82
ART_AND_DESIGN           64
EVENTS                   64
COMICS                   60
PARENTING                60
BEAUTY                   53
Name: Type, dtype: int64

In [20]:
df_pr = df[df['Type']=='Free']
df_pr.groupby('Category')['Type'].count().sort_values(ascending = False)

Category
FAMILY                 1778
GAME                   1061
TOOLS                   764
BUSINESS                446
PRODUCTIVITY            396
LIFESTYLE               363
SPORTS                  360
COMMUNICATION           360
MEDICAL                 354
FINANCE                 349
HEALTH_AND_FITNESS      325
PHOTOGRAPHY             313
PERSONALIZATION         308
SOCIAL                  292
NEWS_AND_MAGAZINES      281
SHOPPING                258
TRAVEL_AND_LOCAL        246
DATING                  227
BOOKS_AND_REFERENCE     202
VIDEO_PLAYERS           171
EDUCATION               152
ENTERTAINMENT           147
MAPS_AND_NAVIGATION     132
FOOD_AND_DRINK          125
HOUSE_AND_HOME           88
LIBRARIES_AND_DEMO       83
AUTO_AND_VEHICLES        82
WEATHER                  74
EVENTS                   63
ART_AND_DESIGN           61
COMICS                   60
PARENTING                58
BEAUTY                   53
Name: Type, dtype: int64

In [22]:
df_pr = df[df['Type']=='Paid']
df_pr.groupby('Category')['Type'].count().sort_values(ascending = False)

Category
FAMILY                 190
MEDICAL                109
GAME                    83
PERSONALIZATION         82
TOOLS                   77
BOOKS_AND_REFERENCE     28
PRODUCTIVITY            28
COMMUNICATION           27
SPORTS                  24
PHOTOGRAPHY             22
LIFESTYLE               19
FINANCE                 17
HEALTH_AND_FITNESS      16
BUSINESS                14
TRAVEL_AND_LOCAL        12
WEATHER                  8
DATING                   7
MAPS_AND_NAVIGATION      5
VIDEO_PLAYERS            4
EDUCATION                4
AUTO_AND_VEHICLES        3
ART_AND_DESIGN           3
SOCIAL                   3
PARENTING                2
ENTERTAINMENT            2
FOOD_AND_DRINK           2
SHOPPING                 2
NEWS_AND_MAGAZINES       2
EVENTS                   1
LIBRARIES_AND_DEMO       1
Name: Type, dtype: int64